import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import request from 'supertest'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { createApp } from '../../src/server/app.js'
import { loadOrCreateConfig } from '../../src/server/config.js'

describe('GET /api/version-check', () => {
  let configDir
  let app
  let fetchSpy
  const token = '1234'

  beforeEach(() => {
    configDir = fs.mkdtempSync(path.join(os.tmpdir(), 'api-version-check-'))
    loadOrCreateConfig(configDir, { roots: ['/tmp/a'], port: 4173 })
    // token is generated by loadOrCreateConfig unless already present in
    // config.json; pin it here so requests below can authenticate.
    const config = JSON.parse(fs.readFileSync(path.join(configDir, 'config.json'), 'utf-8'))
    config.token = token
    fs.writeFileSync(path.join(configDir, 'config.json'), JSON.stringify(config, null, 2))

    // Spying on global fetch (rather than only unit-testing checkLatestVersion
    // in isolation) is what actually proves the "zero outbound requests when
    // disabled" claim end-to-end: if the route ever called fetch regardless
    // of the setting, this spy would record the call and the assertion below
    // would fail instead of silently passing.
    fetchSpy = vi.spyOn(globalThis, 'fetch')

    const logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() }
    app = createApp({
      config: { token, roots: ['/tmp/a'] },
      logger,
      getUptimeSeconds: () => 0,
      packageVersion: '0.1.0',
      onShutdown: vi.fn(),
      roots: [{ id: 0, path: '/tmp/a', name: 'a' }],
      configDir,
    })
  })

  afterEach(() => {
    fetchSpy.mockRestore()
    fs.rmSync(configDir, { recursive: true, force: true })
  })

  it('does not call fetch at all when checkForUpdates is disabled (default)', async () => {
    const res = await request(app).get('/api/version-check').set('X-Auth-Token', token)
    expect(res.status).toBe(200)
    expect(res.body).toEqual({ enabled: false })
    expect(fetchSpy).not.toHaveBeenCalled()
  })

  it('performs the check and reports updateAvailable when enabled', async () => {
    fetchSpy.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ version: '9.9.9' }),
    })

    await request(app)
      .put('/api/settings')
      .set('X-Auth-Token', token)
      .send({ checkForUpdates: true })

    const res = await request(app).get('/api/version-check').set('X-Auth-Token', token)
    expect(res.status).toBe(200)
    expect(res.body.enabled).toBe(true)
    expect(res.body.currentVersion).toBe('0.1.0')
    expect(res.body.latestVersion).toBe('9.9.9')
    expect(res.body.updateAvailable).toBe(true)
    expect(fetchSpy).toHaveBeenCalledTimes(1)
  })

  it('reports a failed check without throwing when the registry is unreachable', async () => {
    fetchSpy.mockRejectedValue(new Error('network error'))

    await request(app)
      .put('/api/settings')
      .set('X-Auth-Token', token)
      .send({ checkForUpdates: true })

    const res = await request(app).get('/api/version-check').set('X-Auth-Token', token)
    expect(res.status).toBe(200)
    expect(res.body).toEqual({
      enabled: true,
      currentVersion: '0.1.0',
      latestVersion: null,
      updateAvailable: false,
    })
  })

  it('requires auth', async () => {
    const res = await request(app).get('/api/version-check')
    expect(res.status).toBe(401)
    expect(fetchSpy).not.toHaveBeenCalled()
  })
})
